version: '3.8'

services:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb_data:/data/db

  flask_app:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: adminpassword
      MONGODB_DBNAME: testdb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend_app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask_app

volumes:
  mongodb_data:
